# Generated by Django 4.1 on 2023-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('points_options', 'Points Options'), ('open_response', 'Open Response'), ('yesno_response', 'YesNo Response'), ('order_choice', 'Order Choice')], default='single_choice', max_length=20)),
                ('is_blank_vote_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('tally', models.JSONField(blank=True, null=True)),
                ('postproc', models.JSONField(blank=True, null=True)),
                ('auths', models.ManyToManyField(related_name='votings', to='base.auth')),
                ('pub_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting', to='base.key')),
                ('questions', models.ManyToManyField(related_name='votings', to='voting.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.TextField()),
                ('points_given', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.question')),
            ],
        ),
    ]
