# Generated by Django 4.1 on 2023-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('points_options', 'Points Options')], default='single_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
