# Generated by Django 4.1 on 2023-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_user_response_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_response_enabled',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('open_response', 'Open Response')], default='single_choice', max_length=20),
        ),
    ]
