# Generated by Django 4.1 on 2023-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_voting_question_voting_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
