# Generated by Django 4.1 on 2023-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_question_user_response_enabled_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'),
             ('open_response', 'Open Response'), ('yesno_response', 'YesNo Response')], default='single_choice', max_length=20),
        ),
    ]
