# Generated by Django 4.1 on 2023-12-17 14:07

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('voter_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(request.models.RequestStatus['ACCEPTED'], 'ACCEPTED'), (request.models.RequestStatus['DECLINED'], 'DECLINED'), (request.models.RequestStatus['PENDING'], 'PENDING')], default='PENDING', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'unique_together': {('voting_id', 'voter_id')},
            },
        ),
    ]
