# Generated by Django 4.1 on 2023-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
