name: Lint PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  conventional-pr:
    runs-on: ubuntu-latest
    steps:
      - name: PR should follow Conventional Commits
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
